# Generated by Django 3.1.1 on 2020-09-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testBLOG', '0002_auto_20200911_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated',
        ),
    ]
