# Generated by Django 3.1.1 on 2020-09-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testBLOG', '0005_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
